-- Add down migration script here
-- SELECT distinct
-- a.slug,
-- snippet(articles_fts,1, '***','***','>>>',2) as matched_title,
-- snippet(articles_fts,2, '***','***','>>>',2) as matched_description,
-- snippet(articles_fts,3, '***','***','>>>',2) as matched_body
-- FROM Articles_fts AS AFTS
-- JOIN  Articles AS A  ON A.oid = AFTS.rowid
-- WHERE Articles_fts MATCH 'ethical'
-- order by rank;

-- select
-- article,
-- snippet(articletags_fts, 1, '***','***','>>>',2) from ArticleTags_fts
-- where  ArticleTags_fts match 'grand' ;
